version: '3.1'
services:
  db-hoc:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbheartofcards
      POSTGRES_USER: heartofcards
      POSTGRES_PASSWORD: heartofcards

      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-hoc:/var/lib/postgresql/data
    ports:
      - "1717:5432"
volumes:
  db-hoc: