version: '3.8'
services:
  db-coracaodascartas:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env

    volumes:
      - db-coracaodascartas:/var/lib/postgresql/data
    ports:
      - "1717:5432"
volumes:
  db-coracaodascartas: