server:
  servlet:
    context-path: /heart-of-cards/v1

spring:
  datasource:
    password: 62442
    url: jdbc:postgresql://localhost:5432/db-heart-of-cards?createDatabaseIfNotExist=true
    username: postgres
  jpa:
    hibernate:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true