spring:
  datasource:
    username: ${POSTGRES_USER}
    url: ${URL_BANCO}
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  docker:
    compose:
      enabled: true