server:
  servlet:
    context-path: /coracao-das-cartas/v2
spring:
  datasource:
    username: coracaodascartas
    url: jdbc:postgresql://localhost:1717/dbcoracaodascartas
    driverClassName: org.postgresql.Driver
    password: coracaodascartas

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'false'
  docker:
    compose:
      enabled: true