server:
  servlet:
    context-path: /coracao-das-cartas/v2
spring:
  datasource:
    username: ${POSTGRES_USER}
    url: ${URL_BANCO}
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'false'
  docker:
    compose:
      enabled: true